### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by 2moveit** [fsprojects/FSharp.Atom#44]
[Enter steps to reproduce below:]

1. I just open Atom
2. Then I tried to open Settings View -> Manage Packages

**Atom Version**: 0.199.0
**System**: 
**Thrown From**: [FSharp](https://github.com/fsprojects/FSharp.Atom) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\micro_000\.atom\packages\FSharp\lib\fsharp.js:843

TypeError: Cannot read property 'path' of null
    at FSharpIDE__parseProjectForEditor$ (C:\Users\micro_000\.atom\packages\FSharp\lib\fsharp.js:843:38)
    at C:\Users\micro_000\.atom\packages\FSharp\lib\fsharp.js:891:14
    at Emitter.module.exports.Emitter.emit (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane-container.js:343:34
    at Emitter.module.exports.Emitter.emit (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:234:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:298:21)
    at tabs-tab.<anonymous> (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:159:24)
    at space-pen-ul.jQuery.event.dispatch (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-ul.elemData.handle (C:\Users\micro_000\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -0:10.9.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
FSharp, v0.2.0
Paket, v0.2.2

# Dev
No dev packages
```

**Comment by 2moveit** [comment]
Happens now directly when I start Atom. Last thing that I did was to update from 1.5.0.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.2.2`

**Comment by 2moveit** [comment]
I removed the Fsharp folder from the .atom\packages folder and installed 0.2.2. Still same issue.

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately , I can't reproduce issue for `0.2.2` so I'm not sure if fix is working. Can You try `0.2.3` ?

**Comment by flq** [comment]
Just downloaded 0.2.3, still happening. Method name sounds as if some project would be involved, but I just installed atom, so there isn't any project present. Is that the problem?

**Comment by Krzysztof-Cieslak** [comment]
@flq, Yes, it is the problem. Thanks for hint, I've managed to reproduce issue :smile: 

I'll should push fix Soon™

**Comment by Krzysztof-Cieslak** [comment]
Fixed push in `0.2.5`

**Comment by flq** [comment]
And installed. That on a Sunday, awesomesauce! :+1:

**Comment by 2moveit** [comment]
Well done. Works. Thanks
